import { IEventType } from '@/types';
import { DUMMY_ORGANIZATIONS } from '.';

export const DUMMY_EVENTS: IEventType[] = [
  {
    id: '1',
    eventTitle: 'Meeting with Team',
    eventStartAt: '2025-09-30T10:00:00',
    eventDateYear: 2025,
    eventDateMonth: 9,
    eventDateDay: 30,
    eventDuration: 60,
    participation: [],
    hostOrganization: DUMMY_ORGANIZATIONS[0],
    hostOrganizationId: DUMMY_ORGANIZATIONS[0].id,
  },
  {
    id: '2',
    eventTitle: 'Doctor Appointment',
    eventStartAt: '2025-09-30T15:00:00',
    eventDateYear: 2025,
    eventDateMonth: 9,
    eventDateDay: 20,
    eventDuration: 30,
    participation: [],
    hostOrganization: DUMMY_ORGANIZATIONS[1],
    hostOrganizationId: DUMMY_ORGANIZATIONS[1].id,
  },
  {
    id: '3',
    eventTitle: 'Lunch with Sarah',
    eventStartAt: '2025-10-01T12:30:00',
    eventDateYear: 2025,
    eventDateMonth: 10,
    eventDateDay: 1,
    eventDuration: 90,
    participation: [],
    hostOrganization: DUMMY_ORGANIZATIONS[2],
    hostOrganizationId: DUMMY_ORGANIZATIONS[2].id,
  },
  {
    id: '4',
    eventTitle: 'Project Deadline',
    eventStartAt: '2025-09-18T23:59:00',
    eventDateYear: 2025,
    eventDateMonth: 9,
    eventDateDay: 18,
    eventDuration: 0,
    participation: [],
    hostOrganization: DUMMY_ORGANIZATIONS[3],
    hostOrganizationId: DUMMY_ORGANIZATIONS[3].id,
  },
  {
    id: '5',
    eventTitle: 'Gym Session',
    eventStartAt: '2025-09-18T18:00:00',
    eventDateYear: 2025,
    eventDateMonth: 9,
    eventDateDay: 18,
    eventDuration: 60,
    participation: [],
    hostOrganization: DUMMY_ORGANIZATIONS[4],
    hostOrganizationId: DUMMY_ORGANIZATIONS[4].id,
  },
];
